# Generated by Django 2.2.12 on 2020-10-22 23:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Airbnb', '0003_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 10, 22, 23, 33, 20, 508687, tzinfo=utc))),
                ('subtotal', models.FloatField(default=0.0)),
                ('commission', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('guestName', models.CharField(max_length=50)),
                ('guestLastName', models.CharField(max_length=50)),
                ('guestEmail', models.EmailField(max_length=254)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Airbnb.Property')),
            ],
        ),
    ]
