# Generated by Django 2.2.12 on 2020-10-22 23:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Airbnb', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 22, 23, 44, 7, 783332, tzinfo=utc)),
        ),
    ]
