# Generated by Django 2.2.12 on 2020-10-22 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Airbnb', '0006_auto_20201022_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default='2020-10-22 23:45:52.832217+00:00', max_length=70),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 22, 23, 45, 52, 832175, tzinfo=utc)),
        ),
    ]
