# Generated by Django 2.2.12 on 2020-10-23 00:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Airbnb', '0007_auto_20201022_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default='2020-10-23 00:05:40.154899+00:00', max_length=70),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 0, 5, 40, 154743, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='DateRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airbnb.Property')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airbnb.Reservation')),
            ],
        ),
    ]
