# Generated by Django 2.2.12 on 2020-10-23 00:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Airbnb', '0009_auto_20201023_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterental',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Airbnb.Reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default='2020-10-23 00:31:51.039275+00:00', max_length=70),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 0, 31, 51, 39238, tzinfo=utc)),
        ),
    ]
